version: '3'

services:
  web:
    image: php:7.3-cli
    container_name: php-app
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: php artisan serve --host=0.0.0.0 --port=8000

  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: nacivnsa_pos4
      MYSQL_USER: nacivnsa_pos4
      MYSQL_PASSWORD: 98042663387Jd
    ports:
      - "3306:3306"
